### ISSUE TITLE
Is it possible you could update this?

### ISSUE THREAD

**Issue by FrostKnight** [JustOff/privacy-badger-me#1]
I would love to have privacy badger be usable again.  Or would I be better off asking someone else?

If this is a won't fix, let me know.
  
I am not particularly good at addon creation or modification but I am willing to test if you make changes.  :)

**Comment by JustOff** [comment]
Sorry, but this will definitely be wontfix, and [here's why](https://forum.palemoon.org/viewtopic.php?f=46&t=13888&p=105468#p105468).

**Comment by FrostKnight** [comment]
Okay, didn't realize there was a better alternative or that it was full of bugs. Thanks for the info!
